# Generated by Django 4.2 on 2023-04-22 18:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="followers",
            field=models.ManyToManyField(
                related_name="followed_by", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
